name: New

on:
  workflow_dispatch:

jobs:
  build-radv-android:
    name: Build RADV for Android
    runs-on: ubuntu-latest

    env:
      ANDROID_NDK_VERSION: r25c
      ANDROID_API_LEVEL: 24
      ANDROID_ARCH: arm64

    steps:
      # 1. Clone Mesa from GitLab
      - name: Clone Mesa
        run: |
          git clone --recursive https://gitlab.freedesktop.org/mesa/mesa.git mesa
          cd mesa
          git submodule update --init --recursive

      # 2. Install dependencies
      - name: Install host tools
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            cmake ninja-build python3-pip pkg-config \
            libxcb-xkb-dev libx11-dev libxcb1-dev \
            libxcb-glx0-dev libxrandr-dev libxshmfence-dev \
            libxkbcommon-dev libexpat1-dev libxcb-present-dev
          pip3 install --user meson

      # 3. Download Android NDK
      - name: Download and unpack NDK
        run: |
          wget -q https://dl.google.com/android/repository/android-ndk-${{ env.ANDROID_NDK_VERSION }}-linux.zip
          unzip -q android-ndk-${{ env.ANDROID_NDK_VERSION }}-linux.zip
          echo "ANDROID_NDK_ROOT=$PWD/android-ndk-${{ env.ANDROID_NDK_VERSION }}" >> $GITHUB_ENV
          echo "PATH=$PWD/android-ndk-${{ env.ANDROID_NDK_VERSION }}/toolchains/llvm/prebuilt/linux-x86_64/bin:$PATH" >> $GITHUB_ENV

      # 4. Create Meson cross-file
      - name: Create cross-android.ini
        run: |
          cat > cross-android.ini << 'EOF'
          [binaries]
          c        = 'aarch64-linux-android${ANDROID_API_LEVEL}-clang'
          cpp      = 'aarch64-linux-android${ANDROID_API_LEVEL}-clang++'
          ar       = 'llvm-ar'
          strip    = 'llvm-strip'

          [properties]
          sys_root = '${ANDROID_NDK_ROOT}/toolchains/llvm/prebuilt/linux-x86_64/sysroot'

          [host_machine]
          system     = 'android'
          cpu_family = 'aarch64'
          cpu        = 'arm64'
          endian     = 'little'
          EOF

      # 5. Configure Meson build
      - name: Meson setup
        run: |
          meson setup build-android \
            --cross-file=cross-android.ini \
            -Dplatforms=android \
            -Dgallium-drivers=radv \
            -Dlibunwind=false \
            -Dvalgrind=false \
            --buildtype=release

      # 6. Build and install
      - name: Build RADV
        run: ninja -C build-android install

      # 7. Package artifacts
      - name: Package outputs
        run: |
          mkdir -p artifacts
          cp build-android/install/lib/libvulkan_radeon.so artifacts/
          cp build-android/install/share/vulkan/radeon_icd.json artifacts/
          cd artifacts
          zip -q radv-android-${{ github.run_number }}.zip *

      # 8. Upload build artifacts
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3.1.2
        with:
          name: radv-android
          path: artifacts/radv-android-*.zip
          retention-days: 5